### ISSUE TITLE
Add code scanning tools

### ISSUE THREAD

**Issue by ds-jkreutzfeld** [ds-jkreutzfeld/continuous-poker-dealer#2]
- Code Coverage 
- CodeQL
- Ensure formatting rules

**Comment by wunschjonas** [comment]
Added Jacoco for Code Coverage. This is the current coverage.

![11_09_22 @2_08_26](https://user-images.githubusercontent.com/117741552/201022752-ceabc159-3c7f-448c-8958-4f375a209479.PNG)

**Comment by wunschjonas** [comment]
New coverage from Jacoco
![11_23_22 @11_11_44](https://user-images.githubusercontent.com/117741552/203521074-d50c4e8c-da39-4867-9ce8-15f1a65b6b3b.PNG)
