### ISSUE TITLE
Improve UI

### ISSUE THREAD

**Issue by ds-jkreutzfeld** [ds-jkreutzfeld/continuous-poker-dealer#5]
The current dealer UI is very basic - it just displays the game log and leaderboard.

This information is important, but the presentation should be improved. Maybe we can have a real poker table to display the moves?
It might be necessary to change the dealer timing for a better presentation. Find the sweet spot between quick games and a nice presentation.

**Comment by wunschjonas** [comment]
**Struktur der Ui** 
Es gibt viele Versionen von Pokertischen, an dem die einzelnen Spieler an den Plätzen (je nach Anzahl) sitzen & der Dealer befindet sich unten in der Mitte. Jeder Spieler würde dann zum Beispiel durch eine Box (mit den jw. Informationen) repräsentiert werden. Die ausgelegten Karten liegen dann in der Mitte vom Tisch.  Hierzu gibt es viele Bilder: https://www.shutterstock.com/de/image-vector/poker-table-blue-cloth-on-dark-1994873354
Eine andere Option wäre wie bei http://live.leanpoker.org/tournament/62ffe0d480701900041c2782 die Spieler in einer Leiste links mit den Informationen zu machen & den Dealer auf die rechte Seite zu setzen. Die gespielten Karten liegen hier dann ebenfalls in der Mitte. Da würde ich dann keinen Pokertisch als Bild verwenden, sondern ein Wallpaper ohne den Rand des Tisches https://www.shutterstock.com/de/image-vector/poker-table-background-green-color-vector-1645872547.

**Comment by wunschjonas** [comment]
Die Bilder für die Ui können lokal im Projekt gespeichert oder immer wieder neu aus dem Internet geladen werden. Das erste ist aber meiner Meinung nach deutlich besser.

**Comment by wunschjonas** [comment]
New elements:
- playerbar that shows all players / the scoreboard
- main section contains the gamelog, desk & pot
